# Generated by Django 5.2.8 on 2025-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('status', models.CharField(choices=[('SENT', 'Envoyé'), ('FAILED', 'Échoué')], max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
            ],
            options={
                'verbose_name': 'Log Email',
                'verbose_name_plural': 'Logs Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('key', models.CharField(help_text='Identifiant unique pour le code (ex: WELCOME)', max_length=50, unique=True, verbose_name='Clé unique')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('body', models.TextField(help_text='Contenu HTML ou Texte', verbose_name='Contenu')),
            ],
            options={
                'verbose_name': "Modèle d'email",
                'verbose_name_plural': "Modèles d'emails",
            },
        ),
    ]
