# Generated by Django 5.1.14 on 2025-11-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status'], name='communicati_status_e10043_idx'),
        ),
    ]
