# Generated by Django 5.2.8 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_event_options_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('EVENT', 'Événement'), ('COMPETITION', 'Compétition'), ('INTERNSHIP', 'Stage'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie'),
        ),
    ]
