# Generated by Django 5.2.8 on 2025-11-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_galleryimage_category'),
        ('core', '0004_remove_category_birth_year_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('COMPETITION', 'Compétition'), ('TRAINING', 'Stage'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyée'), ('CONFIRMED', 'Confirmée'), ('DECLINED', 'Refusée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='content.event', verbose_name='Événement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='core.member', verbose_name='Adhérent')),
            ],
            options={
                'verbose_name': 'Convocation',
                'verbose_name_plural': 'Convocations',
                'unique_together': {('event', 'member')},
            },
        ),
    ]
