# Generated by Django 5.1.14 on 2025-11-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_event_type_convocation'),
        ('core', '0006_alter_registration_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_time'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AddIndex(
            model_name='convocation',
            index=models.Index(fields=['status'], name='content_con_status_859247_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='content_eve_start_t_3a7f52_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['category'], name='content_gal_categor_729259_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['uploaded_at'], name='content_gal_uploade_f58bc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='event_start_time_before_end_time'),
        ),
    ]
