# Generated by Django 5.2.8 on 2025-11-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix de la cotisation')),
                ('birth_year_min', models.IntegerField(blank=True, null=True, verbose_name='Année de naissance min')),
                ('birth_year_max', models.IntegerField(blank=True, null=True, verbose_name='Année de naissance max')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Saison',
                'verbose_name_plural': 'Saisons',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='member',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='members/medical/', verbose_name='Certificat médical'),
        ),
        migrations.AddField(
            model_name='member',
            name='medical_certificate_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Validité certificat'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro de licence'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.category', verbose_name='Catégorie')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.member', verbose_name='Adhérent')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='core.season', verbose_name='Saison')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('member', 'season')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.registration', verbose_name='Inscription'),
        ),
    ]
