# Generated by Django 5.2.8 on 2025-11-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_has_passport_member_parent_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='birth_year_max',
        ),
        migrations.RemoveField(
            model_name='category',
            name='birth_year_min',
        ),
        migrations.AddField(
            model_name='category',
            name='age_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Âge maximum'),
        ),
        migrations.AddField(
            model_name='category',
            name='age_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Âge minimum'),
        ),
    ]
