# Generated by Django 5.1.14 on 2025-11-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_category_birth_year_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Remise manuelle (€)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Remise manuelle (%)'),
        ),
    ]
