# Generated by Django 5.1.14 on 2025-11-28 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registration_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-start_date'], 'verbose_name': 'Saison', 'verbose_name_plural': 'Saisons'},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['date_issued'], name='core_invoic_date_is_8afe1c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='core_invoic_status_3d8780_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['email'], name='core_member_email_1c8df0_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name'], name='core_member_last_na_5c71be_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status'], name='core_regist_status_25b876_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['paid'], name='core_regist_paid_4c7df9_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('age_min__lte', models.F('age_max'))), name='category_age_min_lte_age_max'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='season_start_date_before_end_date'),
        ),
    ]
