# Generated by Django 5.1.14 on 2025-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_registration_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='weight_category',
            field=models.CharField(blank=True, choices=[('-30', '-30 kg'), ('-32', '-32 kg'), ('-34', '-34 kg'), ('-36', '-36 kg'), ('-38', '-38 kg'), ('-40', '-40 kg'), ('-42', '-42 kg'), ('-44', '-44 kg'), ('-46', '-46 kg'), ('-48', '-48 kg'), ('-50', '-50 kg'), ('-52', '-52 kg'), ('-55', '-55 kg'), ('-57', '-57 kg'), ('-60', '-60 kg'), ('-63', '-63 kg'), ('-66', '-66 kg'), ('-70', '-70 kg'), ('-73', '-73 kg'), ('-78', '-78 kg'), ('-81', '-81 kg'), ('-90', '-90 kg'), ('-100', '-100 kg'), ('+100', '+100 kg'), ('+78', '+78 kg')], max_length=10, null=True, verbose_name='Catégorie de poids'),
        ),
    ]
