# Generated by Django 5.1.14 on 2025-11-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member_weight_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='weight_category',
            field=models.CharField(blank=True, choices=[('-20', '-20 kg'), ('-23', '-23 kg'), ('-26', '-26 kg'), ('-29', '-29 kg'), ('+29', '+29 kg'), ('-32', '-32 kg'), ('-35', '-35 kg'), ('+46', '+46 kg'), ('-28', '-28 kg'), ('-30', '-30 kg'), ('-34', '-34 kg'), ('-38', '-38 kg'), ('-42', '-42 kg'), ('-46', '-46 kg'), ('-50', '-50 kg'), ('-55', '-55 kg'), ('-60', '-60 kg'), ('-66', '-66 kg'), ('+66', '+66 kg'), ('+63', '+63 kg'), ('-36', '-36 kg'), ('-40', '-40 kg'), ('-44', '-44 kg'), ('-48', '-48 kg'), ('-52', '-52 kg'), ('-57', '-57 kg'), ('-63', '-63 kg'), ('-70', '-70 kg'), ('-73', '-73 kg'), ('-78', '-78 kg'), ('-81', '-81 kg'), ('-90', '-90 kg'), ('-100', '-100 kg'), ('+70', '+70 kg'), ('+73', '+73 kg'), ('+78', '+78 kg'), ('+90', '+90 kg'), ('+100', '+100 kg')], max_length=10, null=True, verbose_name='Catégorie de poids'),
        ),
    ]
