# Generated by Django 5.1.14 on 2025-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_member_weight_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='installments_paid',
            field=models.IntegerField(default=0, verbose_name='Mensualités payées'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_mode',
            field=models.CharField(choices=[('FULL', 'Comptant'), ('3X', '3 Fois')], default='FULL', max_length=10, verbose_name='Mode de paiement'),
        ),
    ]
