# Generated by Django 5.1.15 on 2025-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_member_belt_member_discipline_member_image_rights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='city_hall_aid',
            field=models.BooleanField(default=False, verbose_name='Aide Mairie'),
        ),
        migrations.AddField(
            model_name='registration',
            name='city_hall_aid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Montant Aide Mairie'),
        ),
        migrations.AddField(
            model_name='registration',
            name='has_supplementary_discipline',
            field=models.BooleanField(default=False, verbose_name='Discipline supplémentaire (+40€)'),
        ),
    ]
