# Generated by Django 5.1.15 on 2025-12-21 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_registration_city_hall_aid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('installments', models.IntegerField(default=1, verbose_name="Nombre d'échéances")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Option de paiement',
                'verbose_name_plural': 'Options de paiement',
            },
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('FULL', 'Comptant'), ('3X', '3 Fois')], default='FULL', max_length=10, null=True, verbose_name='Mode de paiement (Legacy)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='core.paymentoption', verbose_name='Option de paiement'),
        ),
    ]
